#!/bin/bash

# variables
CA_CERTS_DIR="/usr/share/ca-certificates"
LCERTS_DIR="${CA_CERTS_DIR}/aurex-certs"
LCERTS_CFG="/etc/ca-certificates.conf"

# functions
get_rel_files(){
   [ -d "$1" ] || return 0
   find "$1" -xtype f -printf "%P\0"
   return 0
}

